# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PBWeekCalendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBWeekCalendar
  #pod 'PBUtils'
  pod 'PBUtils', :path => '../../PBUtils'

  target 'PBWeekCalendarTests' do
    # Pods for testing
  end

end

target 'PBWeekCalendarExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBWeekCalendarExamples
  pod 'PBWeekCalendar', :path => '../.'

end
